const videos = [
  {
    episode: "18/18",
    comments: "11",
    views: "9141",
    title: "The Seven Deadly Sins: Wrath of the Gods",
    categories: ["Active", "Movie"],
    image: require("assets/img/trending/trend-1.jpg"),
  },
  {
    episode: "18/18",
    comments: "11",
    views: "9141",
    title: "Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien",
    categories: ["Active", "Movie"],
    image: require("assets/img/trending/trend-2.jpg"),
  },
  {
    episode: "18/18",
    comments: "11",
    views: "9141",
    title: "Shingeki no Kyojin Season 3 Part 2",
    categories: ["Active", "Movie"],
    image: require("assets/img/trending/trend-3.jpg"),
  },
  {
    episode: "18/18",
    comments: "11",
    views: "9141",
    title: "Fullmetal Alchemist: Brotherhood",
    categories: ["Active", "Movie"],
    image: require("assets/img/trending/trend-4.jpg"),
  },
  {
    episode: "18/18",
    comments: "11",
    views: "9141",
    title: "Shiratorizawa Gakuen Koukou",
    categories: ["Active", "Movie"],
    image: require("assets/img/trending/trend-5.jpg"),
  },
  {
    episode: "18/18",
    comments: "11",
    views: "9141",
    title: "Code Geass: Hangyaku no Lelouch R2",
    categories: ["Active", "Movie"],
    image: require("assets/img/trending/trend-6.jpg"),
  },
  {
    episode: "18/18",
    comments: "11",
    views: "9141",
    title: "Sen to Chihiro no Kamikakushi",
    categories: ["Active", "Movie"],
    image: require("assets/img/popular/popular-1.jpg"),
  },
  {
    episode: "18/18",
    comments: "11",
    views: "9141",
    title: "Kizumonogatari III: Reiket su-hen",
    categories: ["Active", "Movie"],
    image: require("assets/img/popular/popular-2.jpg"),
  },
  {
    episode: "18/18",
    comments: "11",
    views: "9141",
    title: "Shirogane Tamashii hen Kouhan sen",
    categories: ["Active", "Movie"],
    image: require("assets/img/popular/popular-3.jpg"),
  },
  {
    episode: "18/18",
    comments: "11",
    views: "9141",
    title: "Rurouni Kenshin: Meiji Kenkaku Romantan",
    categories: ["Active", "Movie"],
    image: require("assets/img/popular/popular-4.jpg"),
  },
  {
    episode: "18/18",
    comments: "11",
    views: "9141",
    title: "Mushishi Zoku Shou 2nd Season",
    categories: ["Active", "Movie"],
    image: require("assets/img/popular/popular-5.jpg"),
  },
  {
    episode: "18/18",
    comments: "11",
    views: "9141",
    title: "Monogatari Series: Second Season",
    categories: ["Active", "Movie"],
    image: require("assets/img/popular/popular-6.jpg"),
  },
];

export default videos;
