const videos = {
  TrendVideos: [
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "The Seven Deadly Sins: Wrath of the Gods",
      categories: ["Active", "Movie"],
      image: require("assets/img/trending/trend-1.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien",
      categories: ["Active", "Movie"],
      image: require("assets/img/trending/trend-2.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Shingeki no Kyojin Season 3 Part 2",
      categories: ["Active", "Movie"],
      image: require("assets/img/trending/trend-3.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Fullmetal Alchemist: Brotherhood",
      categories: ["Active", "Movie"],
      image: require("assets/img/trending/trend-4.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Shiratorizawa Gakuen Koukou",
      categories: ["Active", "Movie"],
      image: require("assets/img/trending/trend-5.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Code Geass: Hangyaku no Lelouch R2",
      categories: ["Active", "Movie"],
      image: require("assets/img/trending/trend-6.jpg"),
    },
  ],
  PopularVideos: [
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Sen to Chihiro no Kamikakushi",
      categories: ["Active", "Movie"],
      image: require("assets/img/popular/popular-1.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Kizumonogatari III: Reiket su-hen",
      categories: ["Active", "Movie"],
      image: require("assets/img/popular/popular-2.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Shirogane Tamashii hen Kouhan sen",
      categories: ["Active", "Movie"],
      image: require("assets/img/popular/popular-3.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Rurouni Kenshin: Meiji Kenkaku Romantan",
      categories: ["Active", "Movie"],
      image: require("assets/img/popular/popular-4.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Mushishi Zoku Shou 2nd Season",
      categories: ["Active", "Movie"],
      image: require("assets/img/popular/popular-5.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Monogatari Series: Second Season",
      categories: ["Active", "Movie"],
      image: require("assets/img/popular/popular-6.jpg"),
    },
  ],
  RecentVideos: [
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Great Teacher Onizuka",
      categories: ["Active", "Movie"],
      image: require("assets/img/recent/recent-1.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Fate/stay night Movie: Heaven's Feel - II. Lost",
      categories: ["Active", "Movie"],
      image: require("assets/img/recent/recent-2.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Mushishi Zoku Shou: Suzu no Shizuku",
      categories: ["Active", "Movie"],
      image: require("assets/img/recent/recent-3.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Fate/Zero 2nd Season",
      categories: ["Active", "Movie"],
      image: require("assets/img/recent/recent-4.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Kizumonogatari II: Nekket su-hen",
      categories: ["Active", "Movie"],
      image: require("assets/img/recent/recent-5.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "The Seven Deadly Sins: Wrath of the Gods",
      categories: ["Active", "Movie"],
      image: require("assets/img/recent/recent-6.jpg"),
    },
  ],
  LiveVideos: [
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Shouwa Genroku Rakugo Shinjuu",
      categories: ["Active", "Movie"],
      image: require("assets/img/live/live-1.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Mushishi Zoku Shou 2nd Season",
      categories: ["Active", "Movie"],
      image: require("assets/img/live/live-2.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Mushishi Zoku Shou: Suzu no Shizuku",
      categories: ["Active", "Movie"],
      image: require("assets/img/live/live-3.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "The Seven Deadly Sins: Wrath of the Gods",
      categories: ["Active", "Movie"],
      image: require("assets/img/live/live-4.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Fate/stay night Movie: Heaven's Feel - II. Lost",
      categories: ["Active", "Movie"],
      image: require("assets/img/live/live-5.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Kizumonogatari II: Nekketsu-hen",
      categories: ["Active", "Movie"],
      image: require("assets/img/live/live-6.jpg"),
    },
  ],
  TopVideos: [
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Boruto: Naruto next generations",
      categories: ["Active", "Movie"],
      image: require("assets/img/sidebar/tv-1.jpg"),
      date:["day", "month"]
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "The Seven Deadly Sins: Wrath of the Gods",
      categories: ["Active", "Movie"],
      image: require("assets/img/sidebar/tv-2.jpg"),
      date:["day", "month"]

    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Sword art online alicization war of underworld",
      categories: ["Active", "Movie"],
      image: require("assets/img/sidebar/tv-3.jpg"),
      date:["day", "year"]

    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Fate/stay night: Heaven's Feel I. presage flower",
      categories: ["Active", "Movie"],
      image: require("assets/img/sidebar/tv-4.jpg"),
      date:["day", "year"]

    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Fate stay night unlimited blade works",
      categories: ["Active", "Movie"],
      image: require("assets/img/sidebar/tv-5.jpg"),
      date:["day", "month"]

    },
    
  ],
  CommentVideos: [
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "The Seven Deadly Sins: Wrath of the Gods",
      categories: ["Active", "Movie"],
      image: require("assets/img/sidebar/comment-1.jpg"),
    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Shirogane Tamashii hen Kouhan sen",
      categories: ["Active", "Movie"],
      image: require("assets/img/sidebar/comment-2.jpg"),

    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Kizumonogatari III: Reiket su-hen",
      categories: ["Active", "Movie"],
      image: require("assets/img/sidebar/comment-3.jpg"),

    },
    {
      episode: "18/18",
      comments: "11",
      views: "9141",
      title: "Monogatari Series: Second Season",
      categories: ["Active", "Movie"],
      image: require("assets/img/sidebar/comment-4.jpg"),

    },
  ],
};

export default videos;
